# Generated by Django 6.0.4 on 2026-04-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
    ]
