# Generated by Django 6.0.4 on 2026-05-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno_es_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo en lista blanca'),
        ),
    ]
