# Generated by Django 6.0.4 on 2026-06-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['nombre_completo'], 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
    ]
