"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# 1. Definir BASE_DIR (Esto debe estar ARRIBA de todo)
BASE_DIR = Path(__file__).resolve().parent.parent

# ... otras configuraciones (SECRET_KEY, DEBUG, etc.) ...

# 2. Ahora sí puedes usarlo para el diccionario
RADIUS_DICT_PATH = os.path.join(BASE_DIR, 'radius_dict', 'dictionary')

BASE_DIR = Path(__file__).resolve().parent.parent

# --- SEGURIDAD CRÍTICA ---
SECRET_KEY = 'django-insecure-@j+4(pld)$n7u&1m3f33jihyftie%23&&oxecvp^yo#c!1d&0x'
DEBUG = False

# Ajusta esto a la IP local de tu servidor y la del controlador Omada
ALLOWED_HOSTS = ['*'] 

# --- CONFIGURACIÓN DE SESIONES Y SEGURIDAD AGREGADA ---
# Estas configuraciones aseguran que las sesiones de los alumnos sean robustas
SESSION_COOKIE_SECURE = False  # Cambiar a True cuando tengas certificado SSL (HTTPS)
CSRF_COOKIE_SECURE = False     # Cambiar a True cuando tengas certificado SSL (HTTPS)
SESSION_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 86400  # 24 horas de sesión activa en el portal

# Protección contra ataques comunes
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000']

# --- DEFINICIÓN DE APLICACIONES ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'alumnos', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'alumnos.middleware.RememberAlumnoMiddleware', # Tu middleware actual
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# --- BASE DE DATOS ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# --- AUTENTICACIÓN ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

AUTHENTICATION_BACKENDS = [
    'alumnos.backends.AlumnoBackend', # Prioridad para alumnos
    'django.contrib.auth.backends.ModelBackend',
]

# --- CONFIGURACIÓN RADIUS PARA OMADA ER605 (NUEVO) ---
# Define aquí los datos de tu servidor RADIUS
RADIUS_SERVER = '127.0.0.1'     # IP donde corre tu FreeRADIUS o servidor de auth
RADIUS_SECRET = b'secret_omada' # Debe coincidir con el del ER605
RADIUS_DICT_PATH = '/usr/share/freeradius/dictionary.rfc2865' # Ruta en Linux (ajustar si usas Windows)

# --- INTERNACIONALIZACIÓN ---
LANGUAGE_CODE = 'es-ar' # Cambiado a español de Argentina
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True

# --- ARCHIVOS ESTÁTICOS ---
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Duración del token de "Recordar"
REMEMBER_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 días